### PR TITLE
fix: cached storage bug + support reentrancy

### LINKED ISSUE #37: [Feature]: Support Reentrancy
### What is the feature you would like to see?

Given a reentrant transaction flow like: `EOA calls Contract A -> Contract A calls Contract B -> Contract B calls back into Contract A`, Motsu would panic. 

Since Motsu is a unit testing framework, it should make no assumptions about reentrancy, and should support it out of the box.

### Contribution Guidelines

- [x] I agree to follow this project's Contribution Guidelines

### PR DESCRIPTION
**Pull request by qalisander**
Resolves #37

#### PR Checklist

- [x] Tests
- [x] Documentation
- [x] Changelog

### CODE REVIEW

File: crates/motsu/src/lib.rs [hunk 1]
```diff
@@ -255,7 +254,28 @@ mod ping_pong_tests {
...
+
+        assert_eq!(alice_ping.contract_address.get(), Address::ZERO);
+        assert_eq!(alice_pong.contract_address.get(), Address::ZERO);
+
+        _ = alice_ping
+            .ping(pong.address(), TEN)
+            .expect("should ping successfully");
+
+        assert_eq!(alice_ping.contract_address.get(), ping.address());
+        assert_eq!(alice_pong.contract_address.get(), pong.address());
```
Comment (qalisander) [inline crates/motsu/src/lib.rs:274]: So, this test was failing on this line before. Because `alice_pong.contract_address.get()` was caching value `Address::ZERO` and on zero was retrieved

File: crates/motsu/src/context.rs [hunk 2]
```diff
@@ -490,25 +497,38 @@ impl<ST: StorageType> ContractCall<'_, ST> {
...
             .replace_contract_address(self.contract_ref.address);
     }
+
+    /// Invalidate the storage cache, by replacing it with an empty storage
+    /// struct.
+    /// Otherwise, instead of expected values, we can receive
+    /// artifacts from the previous invocations.
+    fn invalidate_storage_cache(&self) {
+        let uncached_storage = unsafe { ST::new(uint!(0_U256), 0) };
+        _ = self.storage.replace(uncached_storage);
```
Comment (qalisander) [inline crates/motsu/src/context.rs:507]: This workaround uses "interior mutability" to invalidate the storage

File: crates/motsu/src/router.rs [hunk 3]
```diff
@@ -113,19 +104,48 @@ impl VMRouterContext {
...
+        &self,
+        selector: u32,
+        input: &[u8],
+    ) -> Option<ArbResult> {
+        self.create().route(selector, input)
+    }
+}
+
+/// A factory for router creation.
+struct RouterFactory<R> {
```
Comment (qalisander) [inline crates/motsu/src/router.rs:128]: And for contract calls, we can use factory for `StorageType`. And `StorageType` will be created per each invocation. So no more locks on reentrant calls

File: crates/motsu/src/lib.rs (hunk 1 above)
Comment (0xNeshi) [reply crates/motsu/src/lib.rs:274]: The more I review PRs for the new motsu release, the more I realize how important it is to expand our test suite for it. 
We should probably run our contracts unit tests for each motsu change, as the test suite there is extensive. I'll actually do so right now.

File: crates/motsu/src/lib.rs [hunk 4]
```diff
@@ -495,7 +539,7 @@ mod proxies_tests {
         assert_eq!(proxy3.balance(), TWO);
     }
 
-    #[motsu_proc::test]
+    #[motsu::test]
     fn no_locks_with_panics() {
         for _ in 0..1000 {
```
Comment (0xNeshi) [inline crates/motsu/src/lib.rs:544]: Does this test verify what it's supposed to? Technically it's running on a single thread..

**Comment by 0xNeshi** [comment]
Check https://github.com/OpenZeppelin/stylus-test-helpers/pull/42

File: crates/motsu/src/context.rs (hunk 2 above)
Comment (0xNeshi) [reply crates/motsu/src/context.rs:507]: Why is the interior mutability necessary here? Can't we just reinitialize the storage without wrapping it in `Cell`?

File: crates/motsu/src/context.rs [hunk 5]
```diff
@@ -490,25 +497,38 @@ impl<ST: StorageType> ContractCall<'_, ST> {
         _ = VMContext::current()
             .replace_contract_address(self.contract_ref.address);
     }
+
+    /// Invalidate the storage cache, by replacing it with an empty storage
+    /// struct.
+    /// Otherwise, instead of expected values, we can receive
+    /// artifacts from the previous invocations.
```
[the remark this answers is not in the document]
Comment (qalisander) [reply crates/motsu/src/context.rs:504]: plural makes sense also

File: crates/motsu/src/context.rs (hunk 2 above)
Comment (bidzyyys) [reply crates/motsu/src/context.rs:507]: Fair question here @0xNeshi

File: crates/motsu/src/context.rs [hunk 6]
```diff
@@ -490,25 +497,38 @@ impl<ST: StorageType> ContractCall<'_, ST> {
...
-impl<ST: StorageType> ::core::ops::Deref for ContractCall<'_, ST> {
+impl<ST: StorageType> Deref for ContractCall<'_, ST> {
     type Target = ST;
 
     #[inline]
     fn deref(&self) -> &Self::Target {
         self.set_call_params();
         VMContext::current().transfer_value();
-        &self.storage
+        self.invalidate_storage_cache();
```
Comment (bidzyyys) [inline crates/motsu/src/context.rs:518]: Why do we need to invalidate here?

File: crates/motsu/src/lib.rs (hunk 1 above)
Comment (qalisander) [reply crates/motsu/src/lib.rs:274]: We're checking it by the end, when using at stylus contracts. But e.g. this problem wasn't failing stylus tests

File: crates/motsu/src/context.rs [hunk 7]
```diff
@@ -490,25 +497,38 @@ impl<ST: StorageType> ContractCall<'_, ST> {
...
 }
 
-impl<ST: StorageType> ::core::ops::DerefMut for ContractCall<'_, ST> {
+impl<ST: StorageType> DerefMut for ContractCall<'_, ST> {
     #[inline]
     fn deref_mut(&mut self) -> &mut Self::Target {
         self.set_call_params();
         VMContext::current().transfer_value();
-        &mut self.storage
+        self.invalidate_storage_cache();
```
Comment (bidzyyys) [inline crates/motsu/src/context.rs:529]: Why do we need to invalidate here?

File: crates/motsu/src/context.rs [hunk 8]
```diff
@@ -490,25 +497,38 @@ impl<ST: StorageType> ContractCall<'_, ST> {
...
+
+        self.storage.get_mut()
```
Comment (bidzyyys) [inline crates/motsu/src/context.rs:531]: Why do you not use `unsafe` code here as in `deref`?

File: crates/motsu/src/context.rs [hunk 9]
```diff
@@ -571,7 +591,7 @@ impl<ST: StorageType + TestRouter + 'static> Contract<ST> {
     #[must_use]
     pub fn sender<A: Into<Address>>(&self, account: A) -> ContractCall<ST> {
         ContractCall {
-            storage: unsafe { ST::new(uint!(0_U256), 0) },
+            storage: Cell::new(unsafe { ST::new(uint!(0_U256), 0) }),
```
Comment (bidzyyys) [inline crates/motsu/src/context.rs:594]: Wdy do we need `Cell`? Why not `RefCell`?

File: crates/motsu/src/context.rs (hunk 2 above)
Comment (qalisander) [reply crates/motsu/src/context.rs:507]: We should dot it `Deref`. We cannot create any new object in function's body, and return reference to it. Moreover `Deref` has the folowing signature`fn deref(&self) -> &Self::Target` and passes just immutable reference. So how would we set the new object then?

File: crates/motsu/src/lib.rs (hunk 4 above)
Comment (bidzyyys) [reply crates/motsu/src/lib.rs:544]: Good question.

File: crates/motsu/src/lib.rs [hunk 10]
```diff
@@ -255,7 +254,28 @@ mod ping_pong_tests {
...
+    fn deref_invalidated_storage_cache(
+        ping: Contract<PingContract>,
+        pong: Contract<PongContract>,
+        alice: Account,
+    ) {
+        let mut alice_ping = ping.sender(alice);
+        let alice_pong = pong.sender(alice);
+
+        assert_eq!(alice_ping.contract_address.get(), Address::ZERO);
+        assert_eq!(alice_pong.contract_address.get(), Address::ZERO);
```
[the remark this answers is not in the document]
Comment (qalisander) [reply crates/motsu/src/lib.rs:267]: `contract::address()` is a part of our mocking suite. One of the tests was checking it

File: crates/motsu/src/router.rs [hunk 11]
```diff
@@ -113,19 +104,48 @@ impl VMRouterContext {
...
+}
+
+/// A trait for router's creation.
+trait CreateRouter: Send + Sync {
+    /// Instantiate a new router.
+    fn create(&self) -> Box<dyn VMRouter>;
+
+    /// Instantiate a new router and instantly route a message to the matching
+    /// selector.
+    /// Returns `None` if the `selector` wasn't found.
```
Comment (bidzyyys) [inline crates/motsu/src/router.rs:117]:
```suggestion
    ///
    /// Returns `None` if the `selector` wasn't found.
```

File: crates/motsu/src/router.rs [hunk 12]
```diff
@@ -113,19 +104,48 @@ impl VMRouterContext {
...
+        selector: u32,
+        input: &[u8],
+    ) -> Option<ArbResult> {
+        self.create().route(selector, input)
+    }
+}
+
+/// A factory for router creation.
+struct RouterFactory<R> {
+    _phantom: PhantomData<R>,
```
Comment (bidzyyys) [inline crates/motsu/src/router.rs:129]:
```suggestion
    phantom: PhantomData<R>,
```

File: crates/motsu/src/context.rs (hunk 2 above)
Comment (0xNeshi) [reply crates/motsu/src/context.rs]: Hmm makes sense. Closing this, as there are other related questions (see https://github.com/OpenZeppelin/stylus-test-helpers/pull/41#discussion_r1946594080 and https://github.com/OpenZeppelin/stylus-test-helpers/pull/41#discussion_r1946593735).

File: crates/motsu/src/context.rs (hunk 9 above)
Comment (0xNeshi) [reply crates/motsu/src/context.rs:594]: Related https://github.com/OpenZeppelin/stylus-test-helpers/pull/41#discussion_r1945981786

File: crates/motsu/src/context.rs (hunk 7 above)
Comment (0xNeshi) [reply crates/motsu/src/context.rs:529]: Related https://github.com/OpenZeppelin/stylus-test-helpers/pull/41#discussion_r1945981786

File: crates/motsu/src/context.rs (hunk 6 above)
Comment (0xNeshi) [reply crates/motsu/src/context.rs:518]: Related https://github.com/OpenZeppelin/stylus-test-helpers/pull/41#discussion_r1945981786

File: crates/motsu/src/context.rs (hunk 8 above)
Comment (qalisander) [reply crates/motsu/src/context.rs:531]: because `get_mut(..)` can accept only mutable reference to self for `Cell` or e.g.`RefCell`. A in `DerefMut` we can pass it. In `Deref` it is impossible (we need to do unsafe conversion).

File: crates/motsu/src/context.rs (hunk 9 above)
Comment (qalisander) [reply crates/motsu/src/context.rs:594]: In our use case `Cell` and `RefCell` are not different. We could use both. But `RefCell` actually uses `Cell` internally, and adds borrow checks during runtime. And these checks only work, when you use `Ref<..>` wrappers that `RefCell` adds when you borrow. As you see we just use an unsafe cast to immutable pointer. So all `RefCell` "safety" warranties are fruitless in our case. And we cannot use `Ref<..>` as a return type for `Deref` because it would require to return not `Ref<..>`, but reference to it `&Ref<..>`. And we cannot return reference to an object created in rust function. 
But the reason we should be safe is: we don't use `ST` contract type as intended by rust. We don't care about any state it has, any variables. But we do care, that it should go each time through shim and retrieve the only VALID state. And not any cached properties.

Comment (qalisander) [reply crates/motsu/src/context.rs:594]: By the end. If you create in stylus contract some simple property, like:
```rust 
    #[storage]
    struct PingContract {
        contract_address: StorageAddress,
    }
```
And call `self.contract_address.get()` multiple times. On the second time the value will be cached in program execution. `self.contract_address.set(new_address)`, will update the cached value and store it into persistent storage.

Comment (qalisander) [reply crates/motsu/src/context.rs:594]: I'm curious also will our contracts be cheaper, if we they would remove that caching feature for simple states..

File: crates/motsu/src/router.rs (hunk 3 above)
Comment (qalisander) [reply crates/motsu/src/router.rs:131]: @0xNeshi and we have a reentrancy test now `call_three_proxies_with_reentrancy`

**Review by 0xNeshi — APPROVED** [review]
